name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  django-build-test:

    runs-on: ubuntu-latest
    environment: DEV
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m pip install django==4.0.3
        python -m pip install crispy_bootstrap4
        python -m pip install base
    - name: Run Tests
      run: |
        python manage.py test
        

    - name: Install cli
      uses: elstudio/action-install-azure-cli@v1


    - name: Log in to Azure
      uses: azure/login@v1.4.3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and deploy Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}
        acrName: mytestacr
        dockerfilePath: ./Dockerfile
  
        
        
