name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  AZURE_WEBAPP_NAME: engagementwebappuni

  
jobs:
  django-build-test:

    runs-on: ubuntu-latest
    environment: DEV
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m pip install django==4.0.3
        python -m pip install crispy_bootstrap4
        python -m pip install base
    - name: Run Tests
      run: |
        python manage.py test
        
    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v3
      with:
        name: python-app
        path: ${{ github.workspace }}
  deploy:
    runs-on: ubuntu-latest
    needs: django-build-test
    steps:

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app
          
      - name: Deployment
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      

   
