name: Azure Container Apps Deploy

on:
  workflow_run:
    workflows: ["Django CI"]
    branches: [main]
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      - uses: actions/checkout@v3
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          
          appSourcePath: ${{ github.workspace }}
          acrName: caf3d2cc044facr
          containerAppName: newcontainer
          resourceGroup: assignment
          
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'ms-employee-engagement-webapp'
          images: 'caf3d2cc044facr.azurecr.io/github-action/container-app:${{ github.sha }}'
